package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.Book;
import ba.unsa.etf.rpr.exception.LibraryException;

import java.util.List;

public class BookManager {
    public Book add(Book book) throws LibraryException {
        if (book.getId() != 0){
            throw new LibraryException("Can't add book with ID. ID is autogenerated");
        }
        try{
            return DaoFactory.booksDao().add(book);
        }catch (LibraryException e){
            throw e;
        }
    }

    public List<Book> getAll() throws LibraryException{
        return DaoFactory.booksDao().getAll();
    }

    public List<Book> getByName(String name) throws LibraryException {
        return DaoFactory.booksDao().getByName(name);
    }

    public Book update(Book book) throws LibraryException {
        try {
            return DaoFactory.booksDao().update(book);
        } catch (LibraryException e) {
            throw e;
        }
    }

    public void delete(Book book) throws LibraryException {
        try {
            DaoFactory.booksDao().delete(book);
        } catch (LibraryException e) {
            throw e;
        }
    }

    public void decreaseBookCount(Book book) throws LibraryException {
        int bookCount = book.getCurrent_book_hold();
        if (bookCount <= 0) {
            delete(book);
        } else {
            book.setCurrent_book_hold(bookCount - 1);
            update(book);
        }
    }

}
