package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.MemberCard;
import ba.unsa.etf.rpr.exception.LibraryException;

import java.util.List;

public class MemberCardManager {
    public MemberCard add(MemberCard memberCard) throws LibraryException {
        if (memberCard.getId() != 0){
            throw new LibraryException("Can't add member with ID. ID is autogenerated");
        }
        try{
            return DaoFactory.members_cardsDao().add(memberCard);
        }catch (LibraryException e){
            throw e;
        }
    }

    public List<MemberCard> getAll() throws LibraryException{
        return DaoFactory.members_cardsDao().getAll();
    }

    public MemberCard update(MemberCard memberCard) throws LibraryException {
        try {
            return DaoFactory.members_cardsDao().update(memberCard);
        } catch (LibraryException e) {
            throw e;
        }
    }

    public void delete(int memberCard) throws LibraryException {
        try {
            DaoFactory.members_cardsDao().delete(memberCard);
        } catch (LibraryException e) {
            throw e;
        }
    }

}
