package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.DaoFactory;


import ba.unsa.etf.rpr.domain.Member;
import ba.unsa.etf.rpr.exception.LibraryException;

import java.util.List;

public class MemberManager {
    public Member add(Member member) throws LibraryException {
        if (member.getId() != 0){
            throw new LibraryException("Can't add member with ID. ID is autogenerated");
        }
        try{
            return DaoFactory.membersDao().add(member);
        }catch (LibraryException e){
            throw e;
        }
    }

    public List<Member> getAll() throws LibraryException{
        return DaoFactory.membersDao().getAll();
    }

    public List<Member> getByName(String name) throws LibraryException {
        return DaoFactory.membersDao().getByName(name);
    }
}
