package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.MemberCard;
import ba.unsa.etf.rpr.exception.LibraryException;

import java.util.List;

/**
 * MemberCardManager with add, getAll, update, delete methods
 * @author dbajramovi3
 */
public class MemberCardManager {
    /**
     * add method
     * @throws LibraryException izuzetak
     * @author dbajramovi3
     */
    public MemberCard add(MemberCard memberCard) throws LibraryException {
        if (memberCard.getId() != 0){
            throw new LibraryException("Can't add member with ID. ID is autogenerated");
        }
        try{
            return DaoFactory.members_cardsDao().add(memberCard);
        }catch (LibraryException e){
            throw e;
        }
    }
    /**
     * get all method
     * @throws LibraryException izuzetak
     * @author dbajramovi3
     */
    public List<MemberCard> getAll() throws LibraryException{
        return DaoFactory.members_cardsDao().getAll();
    }
    /**
     * update method
     * @throws LibraryException
     * @author dbajramovi3
     */
    public MemberCard update(MemberCard memberCard) throws LibraryException {
        try {
            return DaoFactory.members_cardsDao().update(memberCard);
        } catch (LibraryException e) {
            throw e;
        }
    }
    /**
     * delete method
     * @throws LibraryException izuzetak
     * @author dbajramovi3
     */
    public void delete(int memberCard) throws LibraryException {
        try {
            DaoFactory.members_cardsDao().delete(memberCard);
        } catch (LibraryException e) {
            throw e;
        }
    }

}
