package ba.unsa.etf.rpr.business;
import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.ShoppingCart;
import ba.unsa.etf.rpr.exception.LibraryException;

import java.util.List;

public class ShoppingCartManager {

    public ShoppingCart add(ShoppingCart shoppingCart) throws LibraryException {
        if (shoppingCart.getId() != 0){
            throw new LibraryException("Can't add member with ID. ID is autogenerated");
        }
        try{
            return DaoFactory.shopping_cartDao().add(shoppingCart);
        }catch (LibraryException e){
            throw e;
        }
    }

    public List<ShoppingCart> getAll() throws LibraryException{
        return DaoFactory.shopping_cartDao().getAll();
    }

    public ShoppingCart update(ShoppingCart shoppingCart) throws LibraryException {
        try {
            return DaoFactory.shopping_cartDao().update(shoppingCart);
        } catch (LibraryException e) {
            throw e;
        }
    }

    public void delete(ShoppingCart shoppingCart) throws LibraryException {
        try {
            DaoFactory.shopping_cartDao().delete(shoppingCart);
        } catch (LibraryException e) {
            throw e;
        }
    }

}
